version: '3.8'

volumes:
  elasticdata:
  redisdata:
  postgres_data:

services:
  etl:
    build:
      context: ./etl_service
      dockerfile: Dockerfile
    container_name: etl_team_1
    depends_on:
      - redis
      - elasticsearch
      - database
    env_file:
      - .env
    restart: always

  fastapi:
    build:
      context: ./api_service
      dockerfile: Dockerfile
    container_name: fastapi_team_1
    depends_on:
      - etl
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

  nginx:
    image: nginx:1.21.6
    container_name: nginx_team_1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    ports:
      - '80:80'
    depends_on:
      - fastapi

  database:
    image: postgres:13.0-alpine
    container_name: database_team_1
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data/
    restart: always

  elasticsearch:
    image: elasticsearch:7.17.4
    environment:
      - discovery.type=single-node
    container_name: elasticsearch_team_1
    volumes:
      - elasticdata:/usr/src/elasticsearch/data
    ports:
      - '9200:9200'
    restart: always

  redis:
    image: redis:6-alpine
    container_name: rediscache_team_1
    volumes:
      - redisdata:/data
    ports:
      - '6379:6379'
    restart: always
