version: '3.8'

volumes:
  elasticdata:
  redisdata:
  postgres_data:


services:
  etl:
    build:
      context: ./etl_service
      dockerfile: Dockerfile
    container_name: ETL_team_1
    depends_on:
      - redis
      - elasticsearch
      - database
    env_file:
      - .env
    restart: always


  fastapi:
    build:
      context: ./api_service
      dockerfile: Dockerfile
    container_name: FASTAPI_team_1
    depends_on:
      - etl
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always


  database:
    image: postgres:13.0-alpine
    container_name: DATABASE_team_1
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data/
    restart: always


  elasticsearch:
    image: elasticsearch:7.17.4
    environment:
      - discovery.type=single-node
    container_name: ELASTICSEARCH_team_1
    volumes:
      - elasticdata:/usr/src/elasticsearch/data
    ports:
      - '9200:9200'
    restart: always


  redis:
    image: redis:6-alpine
    container_name: REDISCACHE_team_1
    restart: always
    volumes:
      - redisdata:/data
    ports:
      - '6379:6379'